# Generated by Django 4.2.22 on 2025-06-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "my_vaccine",
            },
        ),
    ]
