# Generated by Django 4.2.22 on 2025-06-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_vaccine"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="vaccine",
            table="vaccines",
        ),
    ]
