# Generated by Django 4.2.22 on 2025-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0004_appointment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="date",
            new_name="vaccination_date",
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("vaccination_date", "time")},
        ),
        migrations.AddField(
            model_name="appointment",
            name="signup_date",
            field=models.DateTimeField(auto_now_add=True, default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="VaccinationSignup",
        ),
    ]
