# Generated by Django 4.2.22 on 2025-07-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0005_rename_date_appointment_vaccination_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("user", "vaccination_date"),
                name="one_appointment_per_user_per_day",
            ),
        ),
    ]
